import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-br' | 'pt-pt' | 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  'pt-br': {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.products': 'Produtos',
    'nav.contact': 'Contato',
    
    // Hero Section
    'hero.title': 'Tradição e Excelência em Equipamentos para Indústrias de Bebidas derivadas da cana-de-açúcar',
    'hero.subtitle': 'Há mais de 30 anos fabricando equipamentos de alta qualidade para a produção de cachaça e bebidas destiladas',
    'hero.cta': 'Fale Conosco',
    'hero.products': 'Ver Produtos',
    
    // Features
    'features.title': 'Por que escolher a Arte & Técnica Lisboa?',
    'features.quality.title': 'Qualidade Premium',
    'features.quality.desc': 'Materiais de alta resistência como cobre martelado e aço inox 304',
    'features.technology.title': 'Tecnologia Moderna',
    'features.technology.desc': 'Equipamentos com sistemas de segurança e eficiência energética',
    'features.experience.title': '30+ Anos de Experiência',
    'features.experience.desc': 'Tradição e expertise reconhecidas em todo o Brasil',
    'features.support.title': 'Suporte Técnico',
    'features.support.desc': 'Consultoria, instalação e manutenção especializada',
    
    // Stats
    'stats.years': 'Anos de Mercado',
    'stats.equipment': 'Equipamentos Fabricados',
    'stats.states': 'Estados Atendidos',
    'stats.countries': 'Países Atendidos',
    'stats.clients': 'Clientes Satisfeitos',
    
    // Products Section
    'products.title': 'Nossos Produtos',
    'products.subtitle': 'Soluções completas para sua destilaria',
    'products.viewAll': 'Ver Catálogo Completo',
    
    // Product Categories
    'products.distillation': 'Destilação',
    'products.distillation.desc': 'Alambiques em cobre, colunas contínuas e caldeiras',
    'products.processing': 'Processamento',
    'products.processing.desc': 'Moendas, filtros rotativos e tachos de cozimento',
    'products.fermentation': 'Fermentação',
    'products.fermentation.desc': 'Dornas, reservatórios e tanques em aço inox',
    'products.aging': 'Envelhecimento',
    'products.aging.desc': 'Barris de carvalho e dornas de madeira nacional',
    'products.bottling': 'Envase',
    'products.bottling.desc': 'Engarrafadoras, rinsers e rosquiadeiras',
    'products.accessories': 'Acessórios',
    'products.accessories.desc': 'Alcoômetros, termômetros e kits de análise',
    
    // About Page
    'about.title': 'Nossa História',
    'about.subtitle': 'Mais de três décadas de dedicação à excelência',
    'about.history': 'A Arte & Técnica Lisboa nasceu da paixão pela tradição brasileira de produção de cachaça. Com mais de 30 anos de experiência, nos tornamos referência nacional na fabricação de equipamentos industriais para destilarias.',
    'about.mission.title': 'Missão',
    'about.mission.desc': 'Fornecer equipamentos de alta qualidade que permitam aos nossos clientes produzir bebidas destiladas de excelência, preservando a tradição e incorporando tecnologia moderna.',
    'about.vision.title': 'Visão',
    'about.vision.desc': 'Ser reconhecida como a principal fornecedora de equipamentos para destilarias no Brasil e na América Latina.',
    'about.values.title': 'Valores',
    'about.values.desc': 'Qualidade, tradição, inovação, compromisso com o cliente e respeito às normas técnicas.',
    
    // Services
    'services.title': 'Nossos Serviços',
    'services.projects': 'Elaboração de Projetos',
    'services.projects.desc': 'Desenvolvimento completo de projetos personalizados para sua destilaria',
    'services.manufacturing': 'Fabricação e Instalação',
    'services.manufacturing.desc': 'Produção de equipamentos e instalação no local',
    'services.sizing': 'Dimensionamento de Fábricas',
    'services.sizing.desc': 'Planejamento e dimensionamento completo da planta industrial',
    'services.consulting': 'Consultoria Técnica',
    'services.consulting.desc': 'Visitas técnicas e orientação especializada',
    'services.training': 'Cursos e Treinamentos',
    'services.training.desc': 'Capacitação para operação e manutenção dos equipamentos',
    'services.standardization': 'Padronização de Produtos',
    'services.standardization.desc': 'Auxílio na padronização da qualidade do destilado',
    
    // Contact Page
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Estamos prontos para atender você',
    'contact.form.name': 'Nome',
    'contact.form.email': 'E-mail',
    'contact.form.phone': 'Telefone',
    'contact.form.message': 'Mensagem',
    'contact.form.submit': 'Enviar Mensagem',
    'contact.info.title': 'Informações de Contato',
    'contact.info.address': 'Endereço',
    'contact.info.phones': 'Telefones',
    'contact.info.email': 'E-mail',
    'contact.info.instagram': 'Instagram',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados',
    'footer.description': 'Fabricação de equipamentos industriais para destilarias desde 1994',
    'footer.quickLinks': 'Links Rápidos',
    'footer.socialMedia': 'Redes Sociais',
    
    // About extras
    'about.historyTitle': 'Mais de 30 Anos de Tradição',
    'about.historyP2': 'Nossa trajetória é marcada pela busca incessante pela excelência. Cada equipamento que produzimos carrega a expertise acumulada ao longo de décadas, combinando técnicas tradicionais de fabricação com tecnologia moderna.',
    'about.historyP3': 'Atendemos destilarias em diversos estados brasileiros e também exportamos para países da América Latina, sempre mantendo o compromisso com a qualidade e o suporte técnico personalizado.',
    'about.differentials': 'Diferenciais Técnicos',
    'about.diff1': 'Soldas neutras para evitar contaminação',
    'about.diff2': 'Válvulas de alívio de pressão e anti-vácuo',
    'about.diff3': 'Sistema de limpeza CIP integrado',
    'about.diff4': 'Conexões em bronze de alta durabilidade',
    'about.diff5': 'Cobre martelado para melhor catálise',
    'about.diff6': 'Aço inox 304 escovado antisséptico',
    'about.diff7': 'Aquecimento versátil: vapor, fogo ou elétrico',
    'about.diff8': 'Conformidade com normas técnicas',
    'about.value.quality': 'Qualidade',
    'about.value.tradition': 'Tradição',
    'about.value.innovation': 'Inovação',
    'about.value.commitment': 'Compromisso',
    
    // Contact extras
    'contact.formTitle': 'Envie uma mensagem',
    'contact.placeholder.name': 'Seu nome completo',
    'contact.placeholder.email': 'seu@email.com',
    'contact.placeholder.phone': '(00) 00000-0000',
    'contact.placeholder.message': 'Como podemos ajudar?',
    'contact.sending': 'Enviando...',
    'contact.success.title': 'Mensagem enviada!',
    'contact.success.desc': 'Entraremos em contato em breve.',
    'contact.error.title': 'Erro ao enviar',
    'contact.error.desc': 'Tente novamente mais tarde.',
    
    // Index CTA
    'cta.title': 'Pronto para começar seu projeto?',
    'cta.subtitle': 'Entre em contato conosco e receba uma consultoria personalizada para sua destilaria.',
    
    // Products page extras
    'products.materialsTitle': 'Materiais de Alta Qualidade',
    'products.copper': 'Cobre Martelado',
    'products.copper.desc': 'Aumenta a área de contato para melhor catálise e neutralização de impurezas.',
    'products.steel': 'Aço Inox 304',
    'products.steel.desc': 'Resistência à corrosão ácida e acabamento escovado antisséptico.',
    'products.wood': 'Madeiras Nobres',
    'products.wood.desc': 'Carvalho europeu e madeiras nacionais para envelhecimento premium.',
    
    // Individual Products
    'product.copperStills': 'Alambiques em Cobre',
    'product.copperStills.desc': 'Fabricados em cobre martelado, polido e envernizado. Equipados com soldas neutras, válvulas de segurança e sistema de limpeza integrado.',
    'product.copperStills.spec1': 'Aquecimento: vapor, fogo direto ou elétrico',
    'product.copperStills.spec2': 'Válvulas de alívio e anti-vácuo',
    'product.copperStills.spec3': 'Portas de inspeção',
    'product.copperStills.spec4': 'Conexões em bronze',
    'product.continuousColumns': 'Colunas Contínuas',
    'product.continuousColumns.desc': 'Desenvolvidas em cobre liso ou martelado para produção em larga escala. Ideais para diversas bebidas destiladas.',
    'product.continuousColumns.spec1': 'Alta produtividade',
    'product.continuousColumns.spec2': 'Fracionamento contínuo',
    'product.continuousColumns.spec3': 'Design modular',
    'product.continuousColumns.spec4': 'Fácil manutenção',
    'product.steamBoilers': 'Caldeiras Geradoras de Vapor',
    'product.steamBoilers.desc': 'Sistemas completos para fornecimento de vapor aos processos de destilação e aquecimento.',
    'product.steamBoilers.spec1': 'Diversos tamanhos',
    'product.steamBoilers.spec2': 'Alta eficiência',
    'product.steamBoilers.spec3': 'Segurança certificada',
    'product.sugarcaneMills': 'Moendas para Cana-de-açúcar',
    'product.sugarcaneMills.desc': 'Projetadas para processar cana inteira ou picada com alto índice de eficiência na extração.',
    'product.sugarcaneMills.spec1': 'Tecnologia moderna',
    'product.sugarcaneMills.spec2': 'Diversas capacidades e potências',
    'product.sugarcaneMills.spec3': 'Alta segurança operacional',
    'product.sugarcaneMills.spec4': 'Manutenção simplificada',
    'product.rotaryFilter': 'Filtro Rotativo',
    'product.rotaryFilter.desc': 'Fabricado em aço inox 304 para filtragem de alta eficiência do caldo de cana.',
    'product.rotaryFilter.spec1': 'Inox 304',
    'product.rotaryFilter.spec2': 'Alta eficiência',
    'product.rotaryFilter.spec3': 'Fácil limpeza',
    'product.cookingVats': 'Tachos de Cozimento',
    'product.cookingVats.desc': 'Para produção de melado, fabricados em aço inox 304 com pés em aço carbono.',
    'product.cookingVats.spec1': 'Aquecimento a vapor',
    'product.cookingVats.spec2': 'Estrutura robusta',
    'product.cookingVats.spec3': 'Diversos tamanhos',
    'product.fermentationVats': 'Dornas de Fermentação',
    'product.fermentationVats.desc': 'Fabricadas em aço inox 304 escovado, disponíveis em diversos modelos e capacidades.',
    'product.fermentationVats.spec1': 'Inox 304 escovado',
    'product.fermentationVats.spec2': 'Fácil higienização',
    'product.fermentationVats.spec3': 'Modelos variados',
    'product.reservoirs': 'Reservatórios',
    'product.reservoirs.desc': 'Tanques em aço inox para armazenamento e preparação do mosto.',
    'product.reservoirs.spec1': 'Diversas capacidades',
    'product.reservoirs.spec2': 'Acabamento sanitário',
    'product.reservoirs.spec3': 'Resistência à corrosão',
    'product.settlingTanks': 'Tanques Decantadores',
    'product.settlingTanks.desc': 'Sistemas para diluição e decantação com design otimizado.',
    'product.settlingTanks.spec1': 'Fundo cônico',
    'product.settlingTanks.spec2': 'Válvulas de descarga',
    'product.settlingTanks.spec3': 'Inox 304',
    'product.oakBarrels': 'Barris de Carvalho Europeu',
    'product.oakBarrels.desc': 'Barris de aproximadamente 200 litros, remontados, reformados, flambados, lixados e pintados.',
    'product.oakBarrels.spec1': '~200 litros',
    'product.oakBarrels.spec2': 'Carvalho europeu',
    'product.oakBarrels.spec3': 'Flambagem controlada',
    'product.oakBarrels.spec4': 'Acabamento profissional',
    'product.woodCasks': 'Dornas de Madeira Nacional',
    'product.woodCasks.desc': 'Disponíveis em diversos formatos incluindo pirâmides. Ideais para envelhecimento de cachaça.',
    'product.woodCasks.spec1': 'Madeiras nacionais diversas',
    'product.woodCasks.spec2': 'Formatos variados',
    'product.woodCasks.spec3': 'Grande capacidade',
    'product.woodCasks.spec4': 'Perfil sensorial único',
    'product.bottlingMachines': 'Engarrafadoras',
    'product.bottlingMachines.desc': 'Máquinas disponíveis em configurações de 2, 4 e 6 bicos para diferentes escalas de produção.',
    'product.bottlingMachines.spec1': '2, 4 ou 6 bicos',
    'product.bottlingMachines.spec2': 'Alta precisão',
    'product.bottlingMachines.spec3': 'Operação simples',
    'product.rinser': 'Rinser (Lavador de Garrafas)',
    'product.rinser.desc': 'Equipamento para limpeza asséptica das garrafas antes do envase.',
    'product.rinser.spec1': 'Limpeza eficiente',
    'product.rinser.spec2': 'Operação rápida',
    'product.rinser.spec3': 'Baixo consumo de água',
    'product.cappers': 'Rosquiadeiras de Tampas',
    'product.cappers.desc': 'Máquinas automáticas ou semiautomáticas para fechamento com torque controlado.',
    'product.cappers.spec1': 'Torque ajustável',
    'product.cappers.spec2': 'Alta velocidade',
    'product.cappers.spec3': 'Diversos tipos de tampas',
    'product.platformCart': 'Carro Plataforma',
    'product.platformCart.desc': 'Equipamento para transporte interno e secagem de garrafas.',
    'product.platformCart.spec1': 'Estrutura robusta',
    'product.platformCart.spec2': 'Fácil manuseio',
    'product.platformCart.spec3': 'Otimiza o fluxo',
    'product.alcoholmeters': 'Alcoômetros',
    'product.alcoholmeters.desc': 'Instrumentos de alta precisão para medição do teor alcoólico.',
    'product.alcoholmeters.spec1': 'Alta precisão',
    'product.alcoholmeters.spec2': 'Fácil leitura',
    'product.alcoholmeters.spec3': 'Calibrados',
    'product.thermometers': 'Termômetros',
    'product.thermometers.desc': 'Termômetros industriais para monitoramento preciso de temperatura.',
    'product.thermometers.spec1': 'Diversas escalas',
    'product.thermometers.spec2': 'Inox',
    'product.thermometers.spec3': 'Longa durabilidade',
    'product.specialFilters': 'Filtros Especiais',
    'product.specialFilters.desc': 'Modelos específicos para diferentes etapas de purificação da bebida.',
    'product.specialFilters.spec1': 'Diversos tipos',
    'product.specialFilters.spec2': 'Alta eficiência',
    'product.specialFilters.spec3': 'Fácil troca',
    'product.analysisKits': 'Kits de Análise',
    'product.analysisKits.desc': 'Conjuntos para verificação de acidez e presença de cobre, essenciais para conformidade regulatória.',
    'product.analysisKits.spec1': 'Kit de acidez',
    'product.analysisKits.spec2': 'Kit de cobre',
    'product.analysisKits.spec3': 'Instruções completas',
    'product.caps': 'Tampas',
    'product.caps.desc': 'Diversos modelos de tampas para garrafas.',
    'product.caps.spec1': 'Vários tamanhos',
    'product.caps.spec2': 'Rosca e pressão',
    'product.caps.spec3': 'Alta qualidade',

    // WhatsApp
    'whatsapp.message': 'Olá! Gostaria de mais informações sobre equipamentos.',

    // Chatbot
    'chatbot.title': 'Atendimento Online',
    'chatbot.welcome': 'Olá! Como posso ajudar você hoje?',
    'chatbot.placeholder': 'Digite sua mensagem...',
    'chatbot.error': 'Desculpe, ocorreu um erro. Tente novamente.',
  },
  'pt-pt': {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.products': 'Produtos',
    'nav.contact': 'Contacto',
    
    // Hero Section
    'hero.title': 'Tradição e Excelência em Equipamentos para Indústrias de Bebidas derivadas da cana-de-açúcar',
    'hero.subtitle': 'Há mais de 30 anos a fabricar equipamentos de alta qualidade para a produção de aguardente e bebidas destiladas',
    'hero.cta': 'Fale Connosco',
    'hero.products': 'Ver Produtos',
    
    // Features
    'features.title': 'Porquê escolher a Arte & Técnica Lisboa?',
    'features.quality.title': 'Qualidade Premium',
    'features.quality.desc': 'Materiais de alta resistência como cobre martelado e aço inox 304',
    'features.technology.title': 'Tecnologia Moderna',
    'features.technology.desc': 'Equipamentos com sistemas de segurança e eficiência energética',
    'features.experience.title': '30+ Anos de Experiência',
    'features.experience.desc': 'Tradição e expertise reconhecidas em todo o Brasil',
    'features.support.title': 'Suporte Técnico',
    'features.support.desc': 'Consultoria, instalação e manutenção especializada',
    
    // Stats
    'stats.years': 'Anos de Mercado',
    'stats.equipment': 'Equipamentos Fabricados',
    'stats.states': 'Estados Atendidos',
    'stats.countries': 'Países Atendidos',
    'stats.clients': 'Clientes Satisfeitos',
    
    // Products Section
    'products.title': 'Os Nossos Produtos',
    'products.subtitle': 'Soluções completas para a sua destilaria',
    'products.viewAll': 'Ver Catálogo Completo',
    
    // Product Categories
    'products.distillation': 'Destilação',
    'products.distillation.desc': 'Alambiques em cobre, colunas contínuas e caldeiras',
    'products.processing': 'Processamento',
    'products.processing.desc': 'Moendas, filtros rotativos e tachos de cozimento',
    'products.fermentation': 'Fermentação',
    'products.fermentation.desc': 'Dornas, reservatórios e tanques em aço inox',
    'products.aging': 'Envelhecimento',
    'products.aging.desc': 'Barris de carvalho e dornas de madeira nacional',
    'products.bottling': 'Engarrafamento',
    'products.bottling.desc': 'Engarrafadoras, rinsers e roscadoras',
    'products.accessories': 'Acessórios',
    'products.accessories.desc': 'Alcoómetros, termómetros e kits de análise',
    
    // About Page
    'about.title': 'A Nossa História',
    'about.subtitle': 'Mais de três décadas de dedicação à excelência',
    'about.history': 'A Arte & Técnica Lisboa nasceu da paixão pela tradição brasileira de produção de aguardente. Com mais de 30 anos de experiência, tornámo-nos referência nacional no fabrico de equipamentos industriais para destilarias.',
    'about.mission.title': 'Missão',
    'about.mission.desc': 'Fornecer equipamentos de alta qualidade que permitam aos nossos clientes produzir bebidas destiladas de excelência, preservando a tradição e incorporando tecnologia moderna.',
    'about.vision.title': 'Visão',
    'about.vision.desc': 'Ser reconhecida como a principal fornecedora de equipamentos para destilarias no Brasil e na América Latina.',
    'about.values.title': 'Valores',
    'about.values.desc': 'Qualidade, tradição, inovação, compromisso com o cliente e respeito às normas técnicas.',
    
    // Services
    'services.title': 'Os Nossos Serviços',
    'services.projects': 'Elaboração de Projetos',
    'services.projects.desc': 'Desenvolvimento completo de projetos personalizados para a sua destilaria',
    'services.manufacturing': 'Fabrico e Instalação',
    'services.manufacturing.desc': 'Produção de equipamentos e instalação no local',
    'services.sizing': 'Dimensionamento de Fábricas',
    'services.sizing.desc': 'Planeamento e dimensionamento completo da planta industrial',
    'services.consulting': 'Consultoria Técnica',
    'services.consulting.desc': 'Visitas técnicas e orientação especializada',
    'services.training': 'Cursos e Formações',
    'services.training.desc': 'Capacitação para operação e manutenção dos equipamentos',
    'services.standardization': 'Padronização de Produtos',
    'services.standardization.desc': 'Auxílio na padronização da qualidade do destilado',
    
    // Contact Page
    'contact.title': 'Entre em Contacto',
    'contact.subtitle': 'Estamos prontos para o atender',
    'contact.form.name': 'Nome',
    'contact.form.email': 'E-mail',
    'contact.form.phone': 'Telefone',
    'contact.form.message': 'Mensagem',
    'contact.form.submit': 'Enviar Mensagem',
    'contact.info.title': 'Informações de Contacto',
    'contact.info.address': 'Morada',
    'contact.info.phones': 'Telefones',
    'contact.info.email': 'E-mail',
    'contact.info.instagram': 'Instagram',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados',
    'footer.description': 'Fabrico de equipamentos industriais para destilarias desde 1994',
    'footer.quickLinks': 'Links Rápidos',
    'footer.socialMedia': 'Redes Sociais',
    
    // About extras
    'about.historyTitle': 'Mais de 30 Anos de Tradição',
    'about.historyP2': 'A nossa trajetória é marcada pela busca incessante pela excelência. Cada equipamento que produzimos transporta a expertise acumulada ao longo de décadas, combinando técnicas tradicionais de fabrico com tecnologia moderna.',
    'about.historyP3': 'Atendemos destilarias em diversos estados brasileiros e também exportamos para países da América Latina, mantendo sempre o compromisso com a qualidade e o suporte técnico personalizado.',
    'about.differentials': 'Diferenciais Técnicos',
    'about.diff1': 'Soldas neutras para evitar contaminação',
    'about.diff2': 'Válvulas de alívio de pressão e anti-vácuo',
    'about.diff3': 'Sistema de limpeza CIP integrado',
    'about.diff4': 'Conexões em bronze de alta durabilidade',
    'about.diff5': 'Cobre martelado para melhor catálise',
    'about.diff6': 'Aço inox 304 escovado antisséptico',
    'about.diff7': 'Aquecimento versátil: vapor, fogo ou elétrico',
    'about.diff8': 'Conformidade com normas técnicas',
    'about.value.quality': 'Qualidade',
    'about.value.tradition': 'Tradição',
    'about.value.innovation': 'Inovação',
    'about.value.commitment': 'Compromisso',
    
    // Contact extras
    'contact.formTitle': 'Envie uma mensagem',
    'contact.placeholder.name': 'O seu nome completo',
    'contact.placeholder.email': 'seu@email.com',
    'contact.placeholder.phone': '(00) 00000-0000',
    'contact.placeholder.message': 'Como podemos ajudar?',
    'contact.sending': 'A enviar...',
    'contact.success.title': 'Mensagem enviada!',
    'contact.success.desc': 'Entraremos em contacto em breve.',
    'contact.error.title': 'Erro ao enviar',
    'contact.error.desc': 'Tente novamente mais tarde.',
    
    // Index CTA
    'cta.title': 'Pronto para começar o seu projeto?',
    'cta.subtitle': 'Entre em contacto connosco e receba uma consultoria personalizada para a sua destilaria.',
    
    // Products page extras
    'products.materialsTitle': 'Materiais de Alta Qualidade',
    'products.copper': 'Cobre Martelado',
    'products.copper.desc': 'Aumenta a área de contacto para melhor catálise e neutralização de impurezas.',
    'products.steel': 'Aço Inox 304',
    'products.steel.desc': 'Resistência à corrosão ácida e acabamento escovado antisséptico.',
    'products.wood': 'Madeiras Nobres',
    'products.wood.desc': 'Carvalho europeu e madeiras nacionais para envelhecimento premium.',
    
    // Individual Products
    'product.copperStills': 'Alambiques em Cobre',
    'product.copperStills.desc': 'Fabricados em cobre martelado, polido e envernizado. Equipados com soldas neutras, válvulas de segurança e sistema de limpeza integrado.',
    'product.copperStills.spec1': 'Aquecimento: vapor, fogo directo ou eléctrico',
    'product.copperStills.spec2': 'Válvulas de alívio e anti-vácuo',
    'product.copperStills.spec3': 'Portas de inspeção',
    'product.copperStills.spec4': 'Conexões em bronze',
    'product.continuousColumns': 'Colunas Contínuas',
    'product.continuousColumns.desc': 'Desenvolvidas em cobre liso ou martelado para produção em larga escala. Ideais para diversas bebidas destiladas.',
    'product.continuousColumns.spec1': 'Alta produtividade',
    'product.continuousColumns.spec2': 'Fracionamento contínuo',
    'product.continuousColumns.spec3': 'Design modular',
    'product.continuousColumns.spec4': 'Fácil manutenção',
    'product.steamBoilers': 'Caldeiras Geradoras de Vapor',
    'product.steamBoilers.desc': 'Sistemas completos para fornecimento de vapor aos processos de destilação e aquecimento.',
    'product.steamBoilers.spec1': 'Diversos tamanhos',
    'product.steamBoilers.spec2': 'Alta eficiência',
    'product.steamBoilers.spec3': 'Segurança certificada',
    'product.sugarcaneMills': 'Moendas para Cana-de-açúcar',
    'product.sugarcaneMills.desc': 'Projetadas para processar cana inteira ou picada com alto índice de eficiência na extração.',
    'product.sugarcaneMills.spec1': 'Tecnologia moderna',
    'product.sugarcaneMills.spec2': 'Diversas capacidades e potências',
    'product.sugarcaneMills.spec3': 'Alta segurança operacional',
    'product.sugarcaneMills.spec4': 'Manutenção simplificada',
    'product.rotaryFilter': 'Filtro Rotativo',
    'product.rotaryFilter.desc': 'Fabricado em aço inox 304 para filtragem de alta eficiência do caldo de cana.',
    'product.rotaryFilter.spec1': 'Inox 304',
    'product.rotaryFilter.spec2': 'Alta eficiência',
    'product.rotaryFilter.spec3': 'Fácil limpeza',
    'product.cookingVats': 'Tachos de Cozimento',
    'product.cookingVats.desc': 'Para produção de melado, fabricados em aço inox 304 com pés em aço carbono.',
    'product.cookingVats.spec1': 'Aquecimento a vapor',
    'product.cookingVats.spec2': 'Estrutura robusta',
    'product.cookingVats.spec3': 'Diversos tamanhos',
    'product.fermentationVats': 'Dornas de Fermentação',
    'product.fermentationVats.desc': 'Fabricadas em aço inox 304 escovado, disponíveis em diversos modelos e capacidades.',
    'product.fermentationVats.spec1': 'Inox 304 escovado',
    'product.fermentationVats.spec2': 'Fácil higienização',
    'product.fermentationVats.spec3': 'Modelos variados',
    'product.reservoirs': 'Reservatórios',
    'product.reservoirs.desc': 'Tanques em aço inox para armazenamento e preparação do mosto.',
    'product.reservoirs.spec1': 'Diversas capacidades',
    'product.reservoirs.spec2': 'Acabamento sanitário',
    'product.reservoirs.spec3': 'Resistência à corrosão',
    'product.settlingTanks': 'Tanques Decantadores',
    'product.settlingTanks.desc': 'Sistemas para diluição e decantação com design otimizado.',
    'product.settlingTanks.spec1': 'Fundo cónico',
    'product.settlingTanks.spec2': 'Válvulas de descarga',
    'product.settlingTanks.spec3': 'Inox 304',
    'product.oakBarrels': 'Barris de Carvalho Europeu',
    'product.oakBarrels.desc': 'Barris de aproximadamente 200 litros, remontados, reformados, flambados, lixados e pintados.',
    'product.oakBarrels.spec1': '~200 litros',
    'product.oakBarrels.spec2': 'Carvalho europeu',
    'product.oakBarrels.spec3': 'Flambagem controlada',
    'product.oakBarrels.spec4': 'Acabamento profissional',
    'product.woodCasks': 'Dornas de Madeira Nacional',
    'product.woodCasks.desc': 'Disponíveis em diversos formatos incluindo pirâmides. Ideais para envelhecimento de aguardente.',
    'product.woodCasks.spec1': 'Madeiras nacionais diversas',
    'product.woodCasks.spec2': 'Formatos variados',
    'product.woodCasks.spec3': 'Grande capacidade',
    'product.woodCasks.spec4': 'Perfil sensorial único',
    'product.bottlingMachines': 'Engarrafadoras',
    'product.bottlingMachines.desc': 'Máquinas disponíveis em configurações de 2, 4 e 6 bicos para diferentes escalas de produção.',
    'product.bottlingMachines.spec1': '2, 4 ou 6 bicos',
    'product.bottlingMachines.spec2': 'Alta precisão',
    'product.bottlingMachines.spec3': 'Operação simples',
    'product.rinser': 'Rinser (Lavador de Garrafas)',
    'product.rinser.desc': 'Equipamento para limpeza asséptica das garrafas antes do engarrafamento.',
    'product.rinser.spec1': 'Limpeza eficiente',
    'product.rinser.spec2': 'Operação rápida',
    'product.rinser.spec3': 'Baixo consumo de água',
    'product.cappers': 'Roscadoras de Tampas',
    'product.cappers.desc': 'Máquinas automáticas ou semiautomáticas para fecho com torque controlado.',
    'product.cappers.spec1': 'Torque ajustável',
    'product.cappers.spec2': 'Alta velocidade',
    'product.cappers.spec3': 'Diversos tipos de tampas',
    'product.platformCart': 'Carro Plataforma',
    'product.platformCart.desc': 'Equipamento para transporte interno e secagem de garrafas.',
    'product.platformCart.spec1': 'Estrutura robusta',
    'product.platformCart.spec2': 'Fácil manuseamento',
    'product.platformCart.spec3': 'Otimiza o fluxo',
    'product.alcoholmeters': 'Alcoómetros',
    'product.alcoholmeters.desc': 'Instrumentos de alta precisão para medição do teor alcoólico.',
    'product.alcoholmeters.spec1': 'Alta precisão',
    'product.alcoholmeters.spec2': 'Fácil leitura',
    'product.alcoholmeters.spec3': 'Calibrados',
    'product.thermometers': 'Termómetros',
    'product.thermometers.desc': 'Termómetros industriais para monitorização precisa de temperatura.',
    'product.thermometers.spec1': 'Diversas escalas',
    'product.thermometers.spec2': 'Inox',
    'product.thermometers.spec3': 'Longa durabilidade',
    'product.specialFilters': 'Filtros Especiais',
    'product.specialFilters.desc': 'Modelos específicos para diferentes etapas de purificação da bebida.',
    'product.specialFilters.spec1': 'Diversos tipos',
    'product.specialFilters.spec2': 'Alta eficiência',
    'product.specialFilters.spec3': 'Fácil troca',
    'product.analysisKits': 'Kits de Análise',
    'product.analysisKits.desc': 'Conjuntos para verificação de acidez e presença de cobre, essenciais para conformidade regulatória.',
    'product.analysisKits.spec1': 'Kit de acidez',
    'product.analysisKits.spec2': 'Kit de cobre',
    'product.analysisKits.spec3': 'Instruções completas',
    'product.caps': 'Tampas',
    'product.caps.desc': 'Diversos modelos de tampas para garrafas.',
    'product.caps.spec1': 'Vários tamanhos',
    'product.caps.spec2': 'Rosca e pressão',
    'product.caps.spec3': 'Alta qualidade',

    // WhatsApp
    'whatsapp.message': 'Olá! Gostaria de mais informações sobre equipamentos.',

    // Chatbot
    'chatbot.title': 'Atendimento Online',
    'chatbot.welcome': 'Olá! Como posso ajudá-lo hoje?',
    'chatbot.placeholder': 'Escreva a sua mensagem...',
    'chatbot.error': 'Desculpe, ocorreu um erro. Tente novamente.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.products': 'Productos',
    'nav.contact': 'Contacto',
    
    // Hero Section
    'hero.title': 'Tradición y Excelencia en Equipos para Destilerías',
    'hero.subtitle': 'Más de 30 años fabricando equipos de alta calidad para la producción de cachaza y bebidas destiladas',
    'hero.cta': 'Contáctenos',
    'hero.products': 'Ver Productos',
    
    // Features
    'features.title': '¿Por qué elegir Arte & Técnica Lisboa?',
    'features.quality.title': 'Calidad Premium',
    'features.quality.desc': 'Materiales de alta resistencia como cobre martillado y acero inox 304',
    'features.technology.title': 'Tecnología Moderna',
    'features.technology.desc': 'Equipos con sistemas de seguridad y eficiencia energética',
    'features.experience.title': '30+ Años de Experiencia',
    'features.experience.desc': 'Tradición y expertise reconocidas en todo Brasil',
    'features.support.title': 'Soporte Técnico',
    'features.support.desc': 'Consultoría, instalación y mantenimiento especializado',
    
    // Stats
    'stats.years': 'Años en el Mercado',
    'stats.equipment': 'Equipos Fabricados',
    'stats.states': 'Estados Atendidos',
    'stats.countries': 'Países Atendidos',
    'stats.clients': 'Clientes Satisfechos',
    
    // Products Section
    'products.title': 'Nuestros Productos',
    'products.subtitle': 'Soluciones completas para su destilería',
    'products.viewAll': 'Ver Catálogo Completo',
    
    // Product Categories
    'products.distillation': 'Destilación',
    'products.distillation.desc': 'Alambiques de cobre, columnas continuas y calderas',
    'products.processing': 'Procesamiento',
    'products.processing.desc': 'Molinos, filtros rotativos y tachos de cocción',
    'products.fermentation': 'Fermentación',
    'products.fermentation.desc': 'Tanques, reservorios y recipientes de acero inox',
    'products.aging': 'Envejecimiento',
    'products.aging.desc': 'Barriles de roble y toneles de madera nacional',
    'products.bottling': 'Embotellado',
    'products.bottling.desc': 'Embotelladoras, rinsers y roscadoras',
    'products.accessories': 'Accesorios',
    'products.accessories.desc': 'Alcoholímetros, termómetros y kits de análisis',
    
    // About Page
    'about.title': 'Nuestra Historia',
    'about.subtitle': 'Más de tres décadas de dedicación a la excelencia',
    'about.history': 'Arte & Técnica Lisboa nació de la pasión por la tradición brasileña de producción de cachaza. Con más de 30 años de experiencia, nos convertimos en referencia nacional en la fabricación de equipos industriales para destilerías.',
    'about.mission.title': 'Misión',
    'about.mission.desc': 'Proporcionar equipos de alta calidad que permitan a nuestros clientes producir bebidas destiladas de excelencia, preservando la tradición e incorporando tecnología moderna.',
    'about.vision.title': 'Visión',
    'about.vision.desc': 'Ser reconocida como la principal proveedora de equipos para destilerías en Brasil y América Latina.',
    'about.values.title': 'Valores',
    'about.values.desc': 'Calidad, tradición, innovación, compromiso con el cliente y respeto a las normas técnicas.',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.projects': 'Elaboración de Proyectos',
    'services.projects.desc': 'Desarrollo completo de proyectos personalizados para su destilería',
    'services.manufacturing': 'Fabricación e Instalación',
    'services.manufacturing.desc': 'Producción de equipos e instalación en sitio',
    'services.sizing': 'Dimensionamiento de Fábricas',
    'services.sizing.desc': 'Planificación y dimensionamiento completo de la planta industrial',
    'services.consulting': 'Consultoría Técnica',
    'services.consulting.desc': 'Visitas técnicas y orientación especializada',
    'services.training': 'Cursos y Capacitaciones',
    'services.training.desc': 'Capacitación para operación y mantenimiento de equipos',
    'services.standardization': 'Estandarización de Productos',
    'services.standardization.desc': 'Asistencia en la estandarización de la calidad del destilado',
    
    // Contact Page
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Estamos listos para atenderle',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Correo electrónico',
    'contact.form.phone': 'Teléfono',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.info.title': 'Información de Contacto',
    'contact.info.address': 'Dirección',
    'contact.info.phones': 'Teléfonos',
    'contact.info.email': 'Correo electrónico',
    'contact.info.instagram': 'Instagram',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados',
    'footer.description': 'Fabricación de equipos industriales para destilerías desde 1994',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.socialMedia': 'Redes Sociales',
    
    // About extras
    'about.historyTitle': 'Más de 30 Años de Tradición',
    'about.historyP2': 'Nuestra trayectoria está marcada por la búsqueda incesante de la excelencia. Cada equipo que producimos lleva la experiencia acumulada a lo largo de décadas, combinando técnicas tradicionales de fabricación con tecnología moderna.',
    'about.historyP3': 'Atendemos destilerías en diversos estados brasileños y también exportamos a países de América Latina, manteniendo siempre el compromiso con la calidad y el soporte técnico personalizado.',
    'about.differentials': 'Diferenciales Técnicos',
    'about.diff1': 'Soldaduras neutras para evitar contaminación',
    'about.diff2': 'Válvulas de alivio de presión y anti-vacío',
    'about.diff3': 'Sistema de limpieza CIP integrado',
    'about.diff4': 'Conexiones en bronce de alta durabilidad',
    'about.diff5': 'Cobre martillado para mejor catálisis',
    'about.diff6': 'Acero inox 304 cepillado antiséptico',
    'about.diff7': 'Calentamiento versátil: vapor, fuego o eléctrico',
    'about.diff8': 'Conformidad con normas técnicas',
    'about.value.quality': 'Calidad',
    'about.value.tradition': 'Tradición',
    'about.value.innovation': 'Innovación',
    'about.value.commitment': 'Compromiso',
    
    // Contact extras
    'contact.formTitle': 'Envíe un mensaje',
    'contact.placeholder.name': 'Su nombre completo',
    'contact.placeholder.email': 'su@correo.com',
    'contact.placeholder.phone': '+00 000 000 0000',
    'contact.placeholder.message': '¿Cómo podemos ayudarle?',
    'contact.sending': 'Enviando...',
    'contact.success.title': '¡Mensaje enviado!',
    'contact.success.desc': 'Nos pondremos en contacto pronto.',
    'contact.error.title': 'Error al enviar',
    'contact.error.desc': 'Inténtelo de nuevo más tarde.',
    
    // Index CTA
    'cta.title': '¿Listo para comenzar su proyecto?',
    'cta.subtitle': 'Contáctenos y reciba una consultoría personalizada para su destilería.',
    
    // Products page extras
    'products.materialsTitle': 'Materiales de Alta Calidad',
    'products.copper': 'Cobre Martillado',
    'products.copper.desc': 'Aumenta el área de contacto para mejor catálisis y neutralización de impurezas.',
    'products.steel': 'Acero Inox 304',
    'products.steel.desc': 'Resistencia a la corrosión ácida y acabado cepillado antiséptico.',
    'products.wood': 'Maderas Nobles',
    'products.wood.desc': 'Roble europeo y maderas nacionales para envejecimiento premium.',
    
    // Individual Products
    'product.copperStills': 'Alambiques de Cobre',
    'product.copperStills.desc': 'Fabricados en cobre martillado, pulido y barnizado. Equipados con soldaduras neutras, válvulas de seguridad y sistema de limpieza integrado.',
    'product.copperStills.spec1': 'Calentamiento: vapor, fuego directo o eléctrico',
    'product.copperStills.spec2': 'Válvulas de alivio y anti-vacío',
    'product.copperStills.spec3': 'Puertas de inspección',
    'product.copperStills.spec4': 'Conexiones en bronce',
    'product.continuousColumns': 'Columnas Continuas',
    'product.continuousColumns.desc': 'Desarrolladas en cobre liso o martillado para producción a gran escala. Ideales para diversas bebidas destiladas.',
    'product.continuousColumns.spec1': 'Alta productividad',
    'product.continuousColumns.spec2': 'Fraccionamiento continuo',
    'product.continuousColumns.spec3': 'Diseño modular',
    'product.continuousColumns.spec4': 'Fácil mantenimiento',
    'product.steamBoilers': 'Calderas Generadoras de Vapor',
    'product.steamBoilers.desc': 'Sistemas completos para suministro de vapor a los procesos de destilación y calentamiento.',
    'product.steamBoilers.spec1': 'Diversos tamaños',
    'product.steamBoilers.spec2': 'Alta eficiencia',
    'product.steamBoilers.spec3': 'Seguridad certificada',
    'product.sugarcaneMills': 'Molinos para Caña de Azúcar',
    'product.sugarcaneMills.desc': 'Diseñados para procesar caña entera o picada con alto índice de eficiencia en la extracción.',
    'product.sugarcaneMills.spec1': 'Tecnología moderna',
    'product.sugarcaneMills.spec2': 'Diversas capacidades y potencias',
    'product.sugarcaneMills.spec3': 'Alta seguridad operacional',
    'product.sugarcaneMills.spec4': 'Mantenimiento simplificado',
    'product.rotaryFilter': 'Filtro Rotativo',
    'product.rotaryFilter.desc': 'Fabricado en acero inox 304 para filtración de alta eficiencia del jugo de caña.',
    'product.rotaryFilter.spec1': 'Inox 304',
    'product.rotaryFilter.spec2': 'Alta eficiencia',
    'product.rotaryFilter.spec3': 'Fácil limpieza',
    'product.cookingVats': 'Tachos de Cocción',
    'product.cookingVats.desc': 'Para producción de melaza, fabricados en acero inox 304 con patas de acero al carbono.',
    'product.cookingVats.spec1': 'Calentamiento a vapor',
    'product.cookingVats.spec2': 'Estructura robusta',
    'product.cookingVats.spec3': 'Diversos tamaños',
    'product.fermentationVats': 'Tanques de Fermentación',
    'product.fermentationVats.desc': 'Fabricados en acero inox 304 cepillado, disponibles en diversos modelos y capacidades.',
    'product.fermentationVats.spec1': 'Inox 304 cepillado',
    'product.fermentationVats.spec2': 'Fácil higienización',
    'product.fermentationVats.spec3': 'Modelos variados',
    'product.reservoirs': 'Reservorios',
    'product.reservoirs.desc': 'Tanques de acero inox para almacenamiento y preparación del mosto.',
    'product.reservoirs.spec1': 'Diversas capacidades',
    'product.reservoirs.spec2': 'Acabado sanitario',
    'product.reservoirs.spec3': 'Resistencia a la corrosión',
    'product.settlingTanks': 'Tanques Decantadores',
    'product.settlingTanks.desc': 'Sistemas para dilución y decantación con diseño optimizado.',
    'product.settlingTanks.spec1': 'Fondo cónico',
    'product.settlingTanks.spec2': 'Válvulas de descarga',
    'product.settlingTanks.spec3': 'Inox 304',
    'product.oakBarrels': 'Barriles de Roble Europeo',
    'product.oakBarrels.desc': 'Barriles de aproximadamente 200 litros, remontados, reformados, flameados, lijados y pintados.',
    'product.oakBarrels.spec1': '~200 litros',
    'product.oakBarrels.spec2': 'Roble europeo',
    'product.oakBarrels.spec3': 'Flameado controlado',
    'product.oakBarrels.spec4': 'Acabado profesional',
    'product.woodCasks': 'Toneles de Madera Nacional',
    'product.woodCasks.desc': 'Disponibles en diversos formatos incluyendo pirámides. Ideales para envejecimiento de cachaza.',
    'product.woodCasks.spec1': 'Maderas nacionales diversas',
    'product.woodCasks.spec2': 'Formatos variados',
    'product.woodCasks.spec3': 'Gran capacidad',
    'product.woodCasks.spec4': 'Perfil sensorial único',
    'product.bottlingMachines': 'Embotelladoras',
    'product.bottlingMachines.desc': 'Máquinas disponibles en configuraciones de 2, 4 y 6 boquillas para diferentes escalas de producción.',
    'product.bottlingMachines.spec1': '2, 4 o 6 boquillas',
    'product.bottlingMachines.spec2': 'Alta precisión',
    'product.bottlingMachines.spec3': 'Operación sencilla',
    'product.rinser': 'Rinser (Lavador de Botellas)',
    'product.rinser.desc': 'Equipo para limpieza aséptica de las botellas antes del embotellado.',
    'product.rinser.spec1': 'Limpieza eficiente',
    'product.rinser.spec2': 'Operación rápida',
    'product.rinser.spec3': 'Bajo consumo de agua',
    'product.cappers': 'Roscadoras de Tapas',
    'product.cappers.desc': 'Máquinas automáticas o semiautomáticas para cierre con torque controlado.',
    'product.cappers.spec1': 'Torque ajustable',
    'product.cappers.spec2': 'Alta velocidad',
    'product.cappers.spec3': 'Diversos tipos de tapas',
    'product.platformCart': 'Carro Plataforma',
    'product.platformCart.desc': 'Equipo para transporte interno y secado de botellas.',
    'product.platformCart.spec1': 'Estructura robusta',
    'product.platformCart.spec2': 'Fácil manejo',
    'product.platformCart.spec3': 'Optimiza el flujo',
    'product.alcoholmeters': 'Alcoholímetros',
    'product.alcoholmeters.desc': 'Instrumentos de alta precisión para medición del contenido alcohólico.',
    'product.alcoholmeters.spec1': 'Alta precisión',
    'product.alcoholmeters.spec2': 'Fácil lectura',
    'product.alcoholmeters.spec3': 'Calibrados',
    'product.thermometers': 'Termómetros',
    'product.thermometers.desc': 'Termómetros industriales para monitoreo preciso de temperatura.',
    'product.thermometers.spec1': 'Diversas escalas',
    'product.thermometers.spec2': 'Inox',
    'product.thermometers.spec3': 'Larga durabilidad',
    'product.specialFilters': 'Filtros Especiales',
    'product.specialFilters.desc': 'Modelos específicos para diferentes etapas de purificación de la bebida.',
    'product.specialFilters.spec1': 'Diversos tipos',
    'product.specialFilters.spec2': 'Alta eficiencia',
    'product.specialFilters.spec3': 'Fácil cambio',
    'product.analysisKits': 'Kits de Análisis',
    'product.analysisKits.desc': 'Conjuntos para verificación de acidez y presencia de cobre, esenciales para conformidad regulatoria.',
    'product.analysisKits.spec1': 'Kit de acidez',
    'product.analysisKits.spec2': 'Kit de cobre',
    'product.analysisKits.spec3': 'Instrucciones completas',
    'product.caps': 'Tapas',
    'product.caps.desc': 'Diversos modelos de tapas para botellas.',
    'product.caps.spec1': 'Varios tamaños',
    'product.caps.spec2': 'Rosca y presión',
    'product.caps.spec3': 'Alta calidad',

    // WhatsApp
    'whatsapp.message': '¡Hola! Me gustaría más información sobre equipos.',

    // Chatbot
    'chatbot.title': 'Atención en Línea',
    'chatbot.welcome': '¡Hola! ¿Cómo puedo ayudarte hoy?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.error': 'Lo siento, ocurrió un error. Inténtalo de nuevo.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.products': 'Products',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Tradition and Excellence in Equipment for Sugarcane Beverage Industries',
    'hero.subtitle': 'Over 30 years manufacturing high-quality equipment for cachaça and distilled beverage production',
    'hero.cta': 'Contact Us',
    'hero.products': 'View Products',
    
    // Features
    'features.title': 'Why choose Arte & Técnica Lisboa?',
    'features.quality.title': 'Premium Quality',
    'features.quality.desc': 'High-resistance materials such as hammered copper and 304 stainless steel',
    'features.technology.title': 'Modern Technology',
    'features.technology.desc': 'Equipment with safety systems and energy efficiency',
    'features.experience.title': '30+ Years of Experience',
    'features.experience.desc': 'Tradition and expertise recognized throughout Brazil',
    'features.support.title': 'Technical Support',
    'features.support.desc': 'Consulting, installation, and specialized maintenance',
    
    // Stats
    'stats.years': 'Years in the Market',
    'stats.equipment': 'Equipment Manufactured',
    'stats.states': 'States Served',
    'stats.countries': 'Countries Served',
    'stats.clients': 'Satisfied Clients',
    
    // Products Section
    'products.title': 'Our Products',
    'products.subtitle': 'Complete solutions for your distillery',
    'products.viewAll': 'View Full Catalog',
    
    // Product Categories
    'products.distillation': 'Distillation',
    'products.distillation.desc': 'Copper stills, continuous columns, and boilers',
    'products.processing': 'Processing',
    'products.processing.desc': 'Mills, rotary filters, and cooking vats',
    'products.fermentation': 'Fermentation',
    'products.fermentation.desc': 'Vats, reservoirs, and stainless steel tanks',
    'products.aging': 'Aging',
    'products.aging.desc': 'Oak barrels and domestic wood casks',
    'products.bottling': 'Bottling',
    'products.bottling.desc': 'Bottling machines, rinsers, and cappers',
    'products.accessories': 'Accessories',
    'products.accessories.desc': 'Alcoholmeters, thermometers, and analysis kits',
    
    // About Page
    'about.title': 'Our History',
    'about.subtitle': 'Over three decades of dedication to excellence',
    'about.history': 'Arte & Técnica Lisboa was born from a passion for the Brazilian tradition of cachaça production. With over 30 years of experience, we have become a national reference in the manufacture of industrial equipment for distilleries.',
    'about.mission.title': 'Mission',
    'about.mission.desc': 'To provide high-quality equipment that enables our clients to produce excellent distilled beverages, preserving tradition while incorporating modern technology.',
    'about.vision.title': 'Vision',
    'about.vision.desc': 'To be recognized as the leading supplier of distillery equipment in Brazil and Latin America.',
    'about.values.title': 'Values',
    'about.values.desc': 'Quality, tradition, innovation, customer commitment, and respect for technical standards.',
    
    // Services
    'services.title': 'Our Services',
    'services.projects': 'Project Development',
    'services.projects.desc': 'Complete development of customized projects for your distillery',
    'services.manufacturing': 'Manufacturing & Installation',
    'services.manufacturing.desc': 'Equipment production and on-site installation',
    'services.sizing': 'Factory Sizing',
    'services.sizing.desc': 'Complete planning and sizing of the industrial plant',
    'services.consulting': 'Technical Consulting',
    'services.consulting.desc': 'Technical visits and specialized guidance',
    'services.training': 'Courses & Training',
    'services.training.desc': 'Training for equipment operation and maintenance',
    'services.standardization': 'Product Standardization',
    'services.standardization.desc': 'Assistance in standardizing distillate quality',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are ready to assist you',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.phones': 'Phones',
    'contact.info.email': 'Email',
    'contact.info.instagram': 'Instagram',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.description': 'Manufacturing industrial equipment for distilleries since 1994',
    'footer.quickLinks': 'Quick Links',
    'footer.socialMedia': 'Social Media',
    
    // About extras
    'about.historyTitle': 'Over 30 Years of Tradition',
    'about.historyP2': 'Our trajectory is marked by an unceasing pursuit of excellence. Every piece of equipment we produce carries the expertise accumulated over decades, combining traditional manufacturing techniques with modern technology.',
    'about.historyP3': 'We serve distilleries across various Brazilian states and also export to Latin American countries, always maintaining our commitment to quality and personalized technical support.',
    'about.differentials': 'Technical Differentials',
    'about.diff1': 'Neutral welds to prevent contamination',
    'about.diff2': 'Pressure relief and anti-vacuum valves',
    'about.diff3': 'Integrated CIP cleaning system',
    'about.diff4': 'High-durability bronze connections',
    'about.diff5': 'Hammered copper for better catalysis',
    'about.diff6': 'Brushed antiseptic 304 stainless steel',
    'about.diff7': 'Versatile heating: steam, fire, or electric',
    'about.diff8': 'Compliance with technical standards',
    'about.value.quality': 'Quality',
    'about.value.tradition': 'Tradition',
    'about.value.innovation': 'Innovation',
    'about.value.commitment': 'Commitment',
    
    // Contact extras
    'contact.formTitle': 'Send us a message',
    'contact.placeholder.name': 'Your full name',
    'contact.placeholder.email': 'your@email.com',
    'contact.placeholder.phone': '+00 000 000 0000',
    'contact.placeholder.message': 'How can we help you?',
    'contact.sending': 'Sending...',
    'contact.success.title': 'Message sent!',
    'contact.success.desc': 'We will get back to you soon.',
    'contact.error.title': 'Error sending',
    'contact.error.desc': 'Please try again later.',
    
    // Index CTA
    'cta.title': 'Ready to start your project?',
    'cta.subtitle': 'Contact us and receive personalized consulting for your distillery.',
    
    // Products page extras
    'products.materialsTitle': 'High-Quality Materials',
    'products.copper': 'Hammered Copper',
    'products.copper.desc': 'Increases the contact area for better catalysis and impurity neutralization.',
    'products.steel': 'Stainless Steel 304',
    'products.steel.desc': 'Acid corrosion resistance and brushed antiseptic finish.',
    'products.wood': 'Noble Woods',
    'products.wood.desc': 'European oak and domestic woods for premium aging.',
    
    // Individual Products
    'product.copperStills': 'Copper Stills',
    'product.copperStills.desc': 'Made of hammered, polished, and varnished copper. Equipped with neutral welds, safety valves, and integrated cleaning system.',
    'product.copperStills.spec1': 'Heating: steam, direct fire, or electric',
    'product.copperStills.spec2': 'Relief and anti-vacuum valves',
    'product.copperStills.spec3': 'Inspection ports',
    'product.copperStills.spec4': 'Bronze connections',
    'product.continuousColumns': 'Continuous Columns',
    'product.continuousColumns.desc': 'Developed in smooth or hammered copper for large-scale production. Ideal for various distilled beverages.',
    'product.continuousColumns.spec1': 'High productivity',
    'product.continuousColumns.spec2': 'Continuous fractionation',
    'product.continuousColumns.spec3': 'Modular design',
    'product.continuousColumns.spec4': 'Easy maintenance',
    'product.steamBoilers': 'Steam Boilers',
    'product.steamBoilers.desc': 'Complete systems for steam supply to distillation and heating processes.',
    'product.steamBoilers.spec1': 'Various sizes',
    'product.steamBoilers.spec2': 'High efficiency',
    'product.steamBoilers.spec3': 'Certified safety',
    'product.sugarcaneMills': 'Sugarcane Mills',
    'product.sugarcaneMills.desc': 'Designed to process whole or chopped sugarcane with high extraction efficiency.',
    'product.sugarcaneMills.spec1': 'Modern technology',
    'product.sugarcaneMills.spec2': 'Various capacities and powers',
    'product.sugarcaneMills.spec3': 'High operational safety',
    'product.sugarcaneMills.spec4': 'Simplified maintenance',
    'product.rotaryFilter': 'Rotary Filter',
    'product.rotaryFilter.desc': 'Made of 304 stainless steel for high-efficiency sugarcane juice filtration.',
    'product.rotaryFilter.spec1': 'Stainless 304',
    'product.rotaryFilter.spec2': 'High efficiency',
    'product.rotaryFilter.spec3': 'Easy cleaning',
    'product.cookingVats': 'Cooking Vats',
    'product.cookingVats.desc': 'For molasses production, made of 304 stainless steel with carbon steel legs.',
    'product.cookingVats.spec1': 'Steam heating',
    'product.cookingVats.spec2': 'Robust structure',
    'product.cookingVats.spec3': 'Various sizes',
    'product.fermentationVats': 'Fermentation Vats',
    'product.fermentationVats.desc': 'Made of brushed 304 stainless steel, available in various models and capacities.',
    'product.fermentationVats.spec1': 'Brushed stainless 304',
    'product.fermentationVats.spec2': 'Easy sanitization',
    'product.fermentationVats.spec3': 'Various models',
    'product.reservoirs': 'Reservoirs',
    'product.reservoirs.desc': 'Stainless steel tanks for storage and must preparation.',
    'product.reservoirs.spec1': 'Various capacities',
    'product.reservoirs.spec2': 'Sanitary finish',
    'product.reservoirs.spec3': 'Corrosion resistance',
    'product.settlingTanks': 'Settling Tanks',
    'product.settlingTanks.desc': 'Systems for dilution and settling with optimized design.',
    'product.settlingTanks.spec1': 'Conical bottom',
    'product.settlingTanks.spec2': 'Discharge valves',
    'product.settlingTanks.spec3': 'Stainless 304',
    'product.oakBarrels': 'European Oak Barrels',
    'product.oakBarrels.desc': 'Approximately 200-liter barrels, reassembled, refurbished, charred, sanded, and painted.',
    'product.oakBarrels.spec1': '~200 liters',
    'product.oakBarrels.spec2': 'European oak',
    'product.oakBarrels.spec3': 'Controlled charring',
    'product.oakBarrels.spec4': 'Professional finish',
    'product.woodCasks': 'Domestic Wood Casks',
    'product.woodCasks.desc': 'Available in various formats including pyramids. Ideal for cachaça aging.',
    'product.woodCasks.spec1': 'Various domestic woods',
    'product.woodCasks.spec2': 'Various formats',
    'product.woodCasks.spec3': 'Large capacity',
    'product.woodCasks.spec4': 'Unique sensory profile',
    'product.bottlingMachines': 'Bottling Machines',
    'product.bottlingMachines.desc': 'Machines available in 2, 4, and 6 nozzle configurations for different production scales.',
    'product.bottlingMachines.spec1': '2, 4, or 6 nozzles',
    'product.bottlingMachines.spec2': 'High precision',
    'product.bottlingMachines.spec3': 'Simple operation',
    'product.rinser': 'Bottle Rinser',
    'product.rinser.desc': 'Equipment for aseptic cleaning of bottles before filling.',
    'product.rinser.spec1': 'Efficient cleaning',
    'product.rinser.spec2': 'Fast operation',
    'product.rinser.spec3': 'Low water consumption',
    'product.cappers': 'Cap Sealers',
    'product.cappers.desc': 'Automatic or semi-automatic machines for controlled torque sealing.',
    'product.cappers.spec1': 'Adjustable torque',
    'product.cappers.spec2': 'High speed',
    'product.cappers.spec3': 'Various cap types',
    'product.platformCart': 'Platform Cart',
    'product.platformCart.desc': 'Equipment for internal transport and bottle drying.',
    'product.platformCart.spec1': 'Robust structure',
    'product.platformCart.spec2': 'Easy handling',
    'product.platformCart.spec3': 'Optimizes workflow',
    'product.alcoholmeters': 'Alcoholmeters',
    'product.alcoholmeters.desc': 'High-precision instruments for alcohol content measurement.',
    'product.alcoholmeters.spec1': 'High precision',
    'product.alcoholmeters.spec2': 'Easy reading',
    'product.alcoholmeters.spec3': 'Calibrated',
    'product.thermometers': 'Thermometers',
    'product.thermometers.desc': 'Industrial thermometers for precise temperature monitoring.',
    'product.thermometers.spec1': 'Various scales',
    'product.thermometers.spec2': 'Stainless steel',
    'product.thermometers.spec3': 'Long durability',
    'product.specialFilters': 'Special Filters',
    'product.specialFilters.desc': 'Specific models for different stages of beverage purification.',
    'product.specialFilters.spec1': 'Various types',
    'product.specialFilters.spec2': 'High efficiency',
    'product.specialFilters.spec3': 'Easy replacement',
    'product.analysisKits': 'Analysis Kits',
    'product.analysisKits.desc': 'Sets for acidity and copper presence verification, essential for regulatory compliance.',
    'product.analysisKits.spec1': 'Acidity kit',
    'product.analysisKits.spec2': 'Copper kit',
    'product.analysisKits.spec3': 'Complete instructions',
    'product.caps': 'Caps',
    'product.caps.desc': 'Various cap models for bottles.',
    'product.caps.spec1': 'Various sizes',
    'product.caps.spec2': 'Screw and press',
    'product.caps.spec3': 'High quality',

    // WhatsApp
    'whatsapp.message': 'Hello! I would like more information about equipment.',

    // Chatbot
    'chatbot.title': 'Online Support',
    'chatbot.welcome': 'Hello! How can I help you today?',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.error': 'Sorry, an error occurred. Please try again.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'pt') return 'pt-br'; // Migrate old 'pt' to 'pt-br'
    return (saved as Language) || 'pt-br';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['pt-br']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
